language: python
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - pytest --cov=tomlcheck
after_success:
  - bash <(curl -s https://codecov.io/bash)
